language: ruby
sudo: required
dist: trusty

services:
- docker

rvm:
- 2.4.4

env:
  global:
  - AWS_REGION='us-east-1'
  - TF_VAR_region=${AWS_REGION}
  - TF_WARN_OUTPUT_ERRORS=1

before_install:
- echo "before_install"

install:
- echo "install"
- gem install bundler --no-rdoc --no-ri
- bundle install

before_script:
- export TERRAFORM_VERSION=0.11.14
- curl --silent --output terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
- unzip terraform.zip ; rm -f terraform.zip; chmod +x terraform
- mkdir -p ${HOME}/bin ; export PATH=${PATH}:${HOME}/bin; mv terraform ${HOME}/bin/
- terraform -v

script:
- echo 'script'
- terraform init
- terraform fmt -check=true
- terraform validate -var "region=${AWS_REGION}" -var "vpc_id=vpc-123456" -var "subnets=[\"subnet-12345a\"]" -var "workers_ami_id=ami-123456" -var "cluster_ingress_cidrs=[]" -var "cluster_name=test_cluster"
- |
  for example in $(find examples -maxdepth 1 -mindepth 1 -type d); do
  cd $example
  terraform init
  terraform fmt -check=true
  terraform validate
  cd -
  done
- terraform -v

notifications:
  email:
    recipients:
    - brandon@atscale.run
    on_success: change
    on_failure: change
