style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/terraform-aws-modules/terraform-aws-eks
options:
  commits:
    sort_by: Type
    filters:
      Type:
        - feat
        - fix
        - improvement
        - docs
        - refactor
        - test
        - ci

  commit_groups:
    group_by: Type
    sort_by: Type
    title_maps:
      feat: FEATURES
      fix: BUG FIXES
      improvement: ENHANCEMENTS
      docs: DOCS
      refactor: REFACTORS
      test: TESTS
      ci: CI

  header:
    pattern: "^(.+)\\s*:\\s*(.+)$"
    pattern_maps:
      - Type
      - Subject

  notes:
    keywords:
      - BREAKING CHANGE
      - NOTES

  refs:
    actions:
      - Closes
      - Fixes
      - Resolves
